debug.CliOptions Class Reference
Class used to analyze the commands passed to the program.
Public Member Functions
CliOptions (String[] args)
Constructor of the CliOption.
int getVerboseLevel ()
Return the verbose level passed as options to the program.
boolean isHelpQueried ()
Return true if the help has been queried or false if not.
Protected Member Functions
void checkVerboseLevel ()
Check the verbose level considering the options with one dash.
void checkHelp ()
Chech if the help mode has been queried considering the options with on or two dashes.
Protected Attributes
int verboseLevel
Level of verbosing detected due to the args passed to the program.
boolean helpQueried
Field equal to true if the help has been queried, false if not.
String oneDashOptions
One letter options passed to the program (corresponding to `one dash` options)
List< String > twoDashesOptions
List of two dashes options passed to the program.
Detailed Description
Class used to analyze the commands passed to the program.
For now, the verbose `-v` can be passed to the program (once or several times) and the help (containing the list of options available) can be queried via --help or -h
You can set a level of verbose mode from 0 to 5, you just have to put -v for verbose mode level 1, -vv for level 2 and so on
Definition at line 18 of file CliOptions.java.
Constructor & Destructor Documentation
debug.CliOptions.CliOptions (String[] args)
Constructor of the CliOption.
Parameters
args Options passed to the program when launching it
Definition at line 52 of file CliOptions.java.
References debug.CliOptions.checkHelp(), debug.CliOptions.checkVerboseLevel(), debug.CliOptions.helpQueried, debug.CliOptions.oneDashOptions, debug.CliOptions.twoDashesOptions, and debug.CliOptions.verboseLevel.
                                     {
        oneDashOptions = new String();
        twoDashesOptions = new LinkedList<String>();
        verboseLevel = 0;
        helpQueried = false;
        // Check the arguments passed to the program
        for(String str : args) {
            // Check if an option is set
            if(str.charAt(0) == '-' && str.length() > 1) {
                // This program support the fact that an option can be prfixed with either '-' or '--'
                if(str.charAt(1) == '-' && str.length() > 2) {
                    
                    twoDashesOptions.add(str.substring(2));
                } else {
                    
                    oneDashOptions += str.substring(1);
                }
                
                
            }
        }
        checkVerboseLevel();
        checkHelp();
    }
Member Function Documentation
void debug.CliOptions.checkHelp () [protected]
Chech if the help mode has been queried considering the options with on or two dashes.
See Also
helpQueried
Definition at line 114 of file CliOptions.java.
References debug.CliOptions.helpQueried, and debug.CliOptions.oneDashOptions.
Referenced by debug.CliOptions.CliOptions().
                               {
        helpQueried = false;
        int oneDashOptionsLength = oneDashOptions.length();
        for(int i = 0 ; i < oneDashOptionsLength ; ++i) {
            if(oneDashOptions.charAt(i) == 'h') {
                helpQueried = true;
                return;
            }
        }
        ListIterator li = twoDashesOptions.listIterator();
        while(li.hasNext()) {
            if(li.next().equals("help")) {
                helpQueried = true;
                return;
            }
        }
    }
void debug.CliOptions.checkVerboseLevel () [protected]
Check the verbose level considering the options with one dash.
See Also
verboseLevel
Definition at line 89 of file CliOptions.java.
References debug.CliOptions.oneDashOptions, and debug.CliOptions.verboseLevel.
Referenced by debug.CliOptions.CliOptions().
                                       {
        verboseLevel = 0;
        
        // Due to performance reasons, the length of the arguments are stored in a variable
        int oneDashOptionsLength = oneDashOptions.length();
        for(int i = 0 ; i < oneDashOptionsLength && verboseLevel < 5 ; ++i) {
            if(oneDashOptions.charAt(i) == 'v')
                ++verboseLevel;
        }
    }
int debug.CliOptions.getVerboseLevel ()
Return the verbose level passed as options to the program.
Returns
The verbose level
Definition at line 106 of file CliOptions.java.
References debug.CliOptions.verboseLevel.
Referenced by main.Philophobia.main().
                                 {
        return verboseLevel;
    }
boolean debug.CliOptions.isHelpQueried ()
Return true if the help has been queried or false if not.
Returns
the helpQueried field
Definition at line 142 of file CliOptions.java.
References debug.CliOptions.helpQueried.
Referenced by main.Philophobia.main().
                                   {
        return helpQueried;
    }
Member Data Documentation
boolean debug.CliOptions.helpQueried [protected]
Field equal to true if the help has been queried, false if not.
If the help has been queried, then the game doesn't launch but instead print all the options that can be passed to the program
Definition at line 34 of file CliOptions.java.
Referenced by debug.CliOptions.checkHelp(), debug.CliOptions.CliOptions(), and debug.CliOptions.isHelpQueried().
String debug.CliOptions.oneDashOptions [protected]
One letter options passed to the program (corresponding to `one dash` options)
Definition at line 40 of file CliOptions.java.
Referenced by debug.CliOptions.checkHelp(), debug.CliOptions.checkVerboseLevel(), and debug.CliOptions.CliOptions().
List<String> debug.CliOptions.twoDashesOptions [protected]
List of two dashes options passed to the program.
Definition at line 45 of file CliOptions.java.
Referenced by debug.CliOptions.CliOptions().
int debug.CliOptions.verboseLevel [protected]
Level of verbosing detected due to the args passed to the program.
See Also
Verbose
Verbose::verboseMode
Definition at line 26 of file CliOptions.java.
Referenced by debug.CliOptions.checkVerboseLevel(), debug.CliOptions.CliOptions(), and debug.CliOptions.getVerboseLevel().
The documentation for this class was generated from the following file:
debug/CliOptions.java