gameplay.ai.mood.PowerComplex Class Reference
Class used to handle the Power Complex mood.
Public Member Functions
PowerComplex ()
PowerComplex main constructor.
int getBetrayalThreshold ()
Getter for the betrayal threshold field.
int getSlaveryThreshold ()
Getter for the slavery threshold field.
int getMoodsBetrayalCount ()
Getter for the betrayal count field.
int getMoodsSlaveryThreshold ()
Getter for the slavery count field.
int incrementBetrayalCount ()
Increment and return the betrayal count field.
int incrementSlaveryCount ()
Increment and return the slavery count field.
Class< Mood > getNextMood ()
When the betrayal threshold is exceeded, this function is called and return a new mood given their probabilities.
Class< Mood > getPreviousMood ()
When the slavery threshold is exceeded, this function is called and return a new mood given their probabilities.
Protected Attributes
int betrayalThreshold
If the betrayal count goes above the betrayal threshold, then the robot must change its current mood (randomness required)
int slaveryThreshold
If the slavery count goes above the betrayal threshold, then the robot must change its current mood (randomness required)
int moodsBetrayalCount
Number of betrayals (requests from the AI not done by the user) done by the user when the AI was currently in this mood state.
int moodsSlaveryCount
Number of requests from the AI done positively by the user when the AI was in this mood state.
HashSet< ProbabilityMood > nextMoods
Associative array containing the possible moods if the number of betrayals (when the AI was in this mood state) is greater than its threshold with the probability associated.
HashSet< ProbabilityMood > previousMoods
Associative array containing the possible moods if the number of done actions asked by the AI is greater than its threshold with the probability associated.
Detailed Description
Class used to handle the Power Complex mood.
Definition at line 8 of file PowerComplex.java.
Constructor & Destructor Documentation
gameplay.ai.mood.PowerComplex.PowerComplex ()
PowerComplex main constructor.
Definition at line 13 of file PowerComplex.java.
                          {
        super(10, 6);
    }
Member Function Documentation
int gameplay.ai.mood.Mood.getBetrayalThreshold () [inherited]
Getter for the betrayal threshold field.
See Also
betrayalThreshold
Definition at line 83 of file Mood.java.
References gameplay.ai.mood.Mood.betrayalThreshold.
                                      {
        return betrayalThreshold;
    }
int gameplay.ai.mood.Mood.getMoodsBetrayalCount () [inherited]
Getter for the betrayal count field.
See Also
moodsBetrayalCount
Definition at line 99 of file Mood.java.
References gameplay.ai.mood.Mood.moodsBetrayalCount.
                                       {
        return moodsBetrayalCount;
    }
int gameplay.ai.mood.Mood.getMoodsSlaveryThreshold () [inherited]
Getter for the slavery count field.
See Also
moodsSlaveryCount
Definition at line 107 of file Mood.java.
References gameplay.ai.mood.Mood.moodsSlaveryCount.
                                          {
        return moodsSlaveryCount;
    }
Class<Mood> gameplay.ai.mood.Mood.getNextMood () [inherited]
When the betrayal threshold is exceeded, this function is called and return a new mood given their probabilities.
Definition at line 132 of file Mood.java.
Referenced by gameplay.ai.AI.newBetrayal().
                                     {
        Iterator<ProbabilityMood> it = nextMoods.iterator();
        ProbabilityMood probMood = null;
        while(it.hasNext()) {
            probMood = it.next();
            if(Math.random() >= probMood.getProbability()) {
                return probMood.getMood();
            }
        }
        return probMood.getMood();
    }
Class<Mood> gameplay.ai.mood.Mood.getPreviousMood () [inherited]
When the slavery threshold is exceeded, this function is called and return a new mood given their probabilities.
Definition at line 152 of file Mood.java.
Referenced by gameplay.ai.AI.newSlavery().
                                         {
        Iterator<ProbabilityMood> it = previousMoods.iterator();
        ProbabilityMood probMood = null;
        while(it.hasNext()) {
            probMood = it.next();
            if(Math.random() >= probMood.getProbability()) {
                return probMood.getMood();
            }
        }
        return probMood.getMood();
    }
int gameplay.ai.mood.Mood.getSlaveryThreshold () [inherited]
Getter for the slavery threshold field.
See Also
slaveryThreshold
Definition at line 91 of file Mood.java.
References gameplay.ai.mood.Mood.slaveryThreshold.
                                     {
        return slaveryThreshold;
    }
int gameplay.ai.mood.Mood.incrementBetrayalCount () [inherited]
Increment and return the betrayal count field.
See Also
moodsBetrayalCount
Definition at line 115 of file Mood.java.
References gameplay.ai.mood.Mood.moodsBetrayalCount.
Referenced by gameplay.ai.AI.newBetrayal().
                                        {
        return ++moodsBetrayalCount;
    }
int gameplay.ai.mood.Mood.incrementSlaveryCount () [inherited]
Increment and return the slavery count field.
See Also
moodsSlaveryCount
Definition at line 123 of file Mood.java.
References gameplay.ai.mood.Mood.moodsSlaveryCount.
Referenced by gameplay.ai.AI.newSlavery().
                                       {
        return ++moodsSlaveryCount;
    }
Member Data Documentation
int gameplay.ai.mood.Mood.betrayalThreshold [protected], [inherited]
If the betrayal count goes above the betrayal threshold, then the robot must change its current mood (randomness required)
Definition at line 24 of file Mood.java.
Referenced by gameplay.ai.mood.Mood.getBetrayalThreshold(), and gameplay.ai.mood.Mood.Mood().
int gameplay.ai.mood.Mood.moodsBetrayalCount [protected], [inherited]
Number of betrayals (requests from the AI not done by the user) done by the user when the AI was currently in this mood state.
Definition at line 41 of file Mood.java.
Referenced by gameplay.ai.mood.Mood.getMoodsBetrayalCount(), and gameplay.ai.mood.Mood.incrementBetrayalCount().
int gameplay.ai.mood.Mood.moodsSlaveryCount [protected], [inherited]
Number of requests from the AI done positively by the user when the AI was in this mood state.
Definition at line 48 of file Mood.java.
Referenced by gameplay.ai.mood.Mood.getMoodsSlaveryThreshold(), and gameplay.ai.mood.Mood.incrementSlaveryCount().
HashSet<ProbabilityMood> gameplay.ai.mood.Mood.nextMoods [protected], [inherited]
Associative array containing the possible moods if the number of betrayals (when the AI was in this mood state) is greater than its threshold with the probability associated.
Definition at line 57 of file Mood.java.
HashSet<ProbabilityMood> gameplay.ai.mood.Mood.previousMoods [protected], [inherited]
Associative array containing the possible moods if the number of done actions asked by the AI is greater than its threshold with the probability associated.
Definition at line 65 of file Mood.java.
int gameplay.ai.mood.Mood.slaveryThreshold [protected], [inherited]
If the slavery count goes above the betrayal threshold, then the robot must change its current mood (randomness required)
Definition at line 32 of file Mood.java.
Referenced by gameplay.ai.mood.Mood.getSlaveryThreshold(), and gameplay.ai.mood.Mood.Mood().
The documentation for this class was generated from the following file:
gameplay/ai/mood/PowerComplex.java