window.ui.UI Class Reference
Class used to handle the window's user interface.
Public Member Functions
UI (int windowHeight, int windowWidth)
UI class constructor.
UI (int windowHeight, int windowWidth, World world)
UI class constructor.
void setDisplayedWorld (World world)
Setter for the displayedWorld field.
void paintComponent (Graphics g)
Function called when the program ask to paint the graphics.
Protected Attributes
World displayedWorld
World displayed inside the window.
int windowHeight
Window height.
int windowWidth
Window width.
Private Member Functions
void drawWorld (Graphics g)
Function called to draw the world.
Detailed Description
Class used to handle the window's user interface.
This class can be in different states
Definition at line 20 of file UI.java.
Constructor & Destructor Documentation
window.ui.UI.UI (int windowHeight, int windowWidth)
UI class constructor.
Parameters
windowHeight Height of the window
windowWidth Width of the window
Definition at line 42 of file UI.java.
References window.ui.UI.windowHeight, and window.ui.UI.windowWidth.
                                                 {
        // We call the parent's constructor
        super();
        Philophobia.getVerbose().calls("Creating UI class", "window/ui/UI.java", "UI.UI(int, int)");
        this.windowHeight = windowHeight;
        this.windowWidth = windowWidth;
    }
window.ui.UI.UI (int windowHeight, int windowWidth, World world)
UI class constructor.
Parameters
windowHeight Height of the window
windowWidth Width of the window
world World to display
Definition at line 59 of file UI.java.
References window.ui.UI.windowHeight, and window.ui.UI.windowWidth.
                                                              {
        super();
        Philophobia.getVerbose().calls("Creating UI class", "window/ui/UI.java", "UI.UI(int, int,World)");
        this.windowHeight = windowHeight;
        this.windowWidth = windowWidth;
        this.displayedWorld = world;
    }
Member Function Documentation
void window.ui.UI.drawWorld (Graphics g) [private]
Function called to draw the world.
This function just display each Scenery one by one but trees are displayed after everything else as they must be on top of everything because of their size
See Also
displayedWorld
Parameters
g Graphics to use
Definition at line 98 of file UI.java.
References world.scenery.Scenery.getSceneryHeight().
Referenced by window.ui.UI.paintComponent().
                                       {
    
        Philophobia.getVerbose().calls("Painting the world", "window/ui/UI.java", "UI.drawWorld(Graphics)")
      ;
        Scenery[][] worldMap = displayedWorld.getMap();
        int worldMapXSize = displayedWorld.getSizeX();
        int worldMapYSize = displayedWorld.getSizeY();
        for(int i = 0 ; i < worldMapXSize ; ++i) {
            for(int j = 0 ; j < worldMapYSize ; ++j) {
                if(!worldMap[i][j].getClass().getName().equals("Tree"))
                    worldMap[i][j].drawScenery(g, i*Scenery.getSceneryHeight(), j*Scenery.getSceneryWidth()
      , this);
            }
        }
        for(int i = 0 ; i < worldMapXSize ; ++i) {
            for(int j = 0 ; j < worldMapYSize ; ++j) {
                if(worldMap[i][j].getClass().getName().equals("Tree"))
                    worldMap[i][j].drawScenery(g, i*Scenery.getSceneryHeight(), j*Scenery.getSceneryWidth()
      , this);
            }
        }
    }
void window.ui.UI.paintComponent (Graphics g)
Function called when the program ask to paint the graphics.
Parameters
g Graphics to use
Definition at line 82 of file UI.java.
References window.ui.UI.drawWorld().
                                           {
        Philophobia.getVerbose().calls("Painting UI components", "window/ui/UI.java", "
      UI.paintComponent(Graphics)");
        super.paintComponent(g);
        drawWorld(g);
    }
void window.ui.UI.setDisplayedWorld (World world)
Setter for the displayedWorld field.
See Also
displayedWorld
Parameters
world World to display
Definition at line 74 of file UI.java.
                                               {
        this.displayedWorld = world;
    }
Member Data Documentation
World window.ui.UI.displayedWorld [protected]
World displayed inside the window.
Definition at line 25 of file UI.java.
int window.ui.UI.windowHeight [protected]
Window height.
Definition at line 30 of file UI.java.
Referenced by window.ui.UI.UI().
int window.ui.UI.windowWidth [protected]
Window width.
Definition at line 35 of file UI.java.
Referenced by window.ui.UI.UI().
The documentation for this class was generated from the following file:
window/ui/UI.java