main.Philophobia Class Reference
Main class.
Static Public Member Functions
static void main (String[] args)
Main function of the program You can set options like verbose mode to the program.
static Verbose getVerbose ()
Getter for the verbose field.
static String getImageFilePrefix ()
Getter for the IMAGE_FILE_PREFIX field.
static String getWorldFilePrefix ()
Getter for the WORLD_FILE_PREFIX field.
static String getPhrasesFilePrefix ()
Static Protected Attributes
static String IMAGE_FILE_PREFIX = `src/images/`
Directory containing all the image files.
static String WORLD_FILE_PREFIX = `src/world/`
Directory containing all the world files.
static String PHRASES_FILE_PREFIX = `src/phrases/`
Directory containing all the phrases files.
static Verbose verbose
Global variable used for debugging.
static GamePlay gamePlay
Main window of the program.
Detailed Description
Main class.
Definition at line 16 of file Philophobia.java.
Member Function Documentation
static String main.Philophobia.getImageFilePrefix () [static]
Getter for the IMAGE_FILE_PREFIX field.
See Also
IMAGE_FILE_PREFIX
Definition at line 91 of file Philophobia.java.
References main.Philophobia.IMAGE_FILE_PREFIX.
Referenced by world.scenery.Flower.Flower(), world.scenery.Grass.Grass(), world.scenery.Ground.Ground(), world.character.Hero.Hero(), world.scenery.Rock.Rock(), world.scenery.Shore.Shore(), world.scenery.Shrub.Shrub(), window.topbar.TopBar.TopBar(), world.scenery.Tree.Tree(), and world.scenery.Water.Water().
                                              {
        return IMAGE_FILE_PREFIX;
    }
static String main.Philophobia.getPhrasesFilePrefix () [static]
Definition at line 103 of file Philophobia.java.
References main.Philophobia.PHRASES_FILE_PREFIX.
Referenced by gameplay.ai.phrasing.Phrasing.Phrasing().
                                                {
        return PHRASES_FILE_PREFIX;
    }
static Verbose main.Philophobia.getVerbose () [static]
Getter for the verbose field.
Returns
The main class verbose static property
Definition at line 83 of file Philophobia.java.
References main.Philophobia.verbose.
                                       {
        return verbose;
    }
static String main.Philophobia.getWorldFilePrefix () [static]
Getter for the WORLD_FILE_PREFIX field.
See Also
WORLD_FILE_PREFIX
Definition at line 99 of file Philophobia.java.
References main.Philophobia.WORLD_FILE_PREFIX.
                                              {
        return WORLD_FILE_PREFIX;
    }
static void main.Philophobia.main (String[] args) [static]
Main function of the program You can set options like verbose mode to the program.
See Also
debug.CliOptions
Parameters
args Global program options (see above)
Definition at line 55 of file Philophobia.java.
References debug.CliOptions.getVerboseLevel(), and debug.CliOptions.isHelpQueried().
                                           {
        
        CliOptions options = new CliOptions(args);
        Philophobia.verbose = new Verbose(options.getVerboseLevel());
        if(!options.isHelpQueried()) {
            // Philophobia.window = new Window();
            Philophobia.gamePlay = new GamePlay(options);
        } else {
    
            System.out.println("");
            System.out.println("Usage: philophobia [options]");
            System.out.println("");
            System.out.println("Options:");
            System.out.println(" Debugging options:");
            System.out.println(" -v Activate verbose mode (to be use multiple times
       for more verbosity)");
            System.out.println(" -h --help Print this help");
            System.out.println("");
        }
            
    }
Member Data Documentation
GamePlay main.Philophobia.gamePlay [static], [protected]
Main window of the program.
Game handler
Definition at line 46 of file Philophobia.java.
String main.Philophobia.IMAGE_FILE_PREFIX = `src/images/` [static], [protected]
Directory containing all the image files.
Definition at line 21 of file Philophobia.java.
Referenced by main.Philophobia.getImageFilePrefix().
String main.Philophobia.PHRASES_FILE_PREFIX = `src/phrases/` [static], [protected]
Directory containing all the phrases files.
Definition at line 31 of file Philophobia.java.
Referenced by main.Philophobia.getPhrasesFilePrefix().
Verbose main.Philophobia.verbose [static], [protected]
Global variable used for debugging.
Definition at line 36 of file Philophobia.java.
Referenced by main.Philophobia.getVerbose().
String main.Philophobia.WORLD_FILE_PREFIX = `src/world/` [static], [protected]
Directory containing all the world files.
Definition at line 26 of file Philophobia.java.
Referenced by main.Philophobia.getWorldFilePrefix().
The documentation for this class was generated from the following file:
main/Philophobia.java