gameplay.ai.AI Class Reference
Class representing the sadistic robot.
Public Member Functions
AI (World currentWorld)
AI class main constructor.
void setCurrentWorld (World world)
Setter for the current world field.
void newBetrayal ()
Method called when the player make a new betrayal (does not do what the AI asked)
void newSlavery ()
Method called when the player do what the AI asked.
Protected Member Functions
void changeMood (Class< Mood > moodClass)
Change the current mood field from a Class object.
Protected Attributes
World currentWorld
World where the player is currently in.
Mood currentMood
Mood in which the AI is currently in.
Phrasing phrasingSystem
AI talk system.
int betrayalCount
Number of betrayals done by the player.
int slaveryCount
Number of asked actions by the AI done by the player.
Detailed Description
Class representing the sadistic robot.
The robot ask the player to do terrible things without taking out the player's choice to do or not to do the task
The AI has a mood system with 4 basic moods : Curiosity, Anger, Depression, Power complex
The robot can switch between these moods considering the user's choices and interact with the environment in a bad way
See Also
gameplay.ai.mood.Mood
Definition at line 32 of file AI.java.
Constructor & Destructor Documentation
gameplay.ai.AI.AI (World currentWorld)
AI class main constructor.
Parameters
currentWorld World where the player is currently in
Definition at line 64 of file AI.java.
References gameplay.ai.AI.betrayalCount, gameplay.ai.AI.currentMood, gameplay.ai.AI.currentWorld, gameplay.ai.AI.phrasingSystem, and gameplay.ai.AI.slaveryCount.
                                  {
        Philophobia.getVerbose().information("Creating sadistic AI", "gameplay/ai/AI.java", "AI.AI(World)")
      ;
        this.currentWorld = currentWorld;
        currentMood = new Curiosity();
        phrasingSystem = new Phrasing();
        betrayalCount = 0;
        slaveryCount = 0;
    }
Member Function Documentation
void gameplay.ai.AI.changeMood (Class< Mood > moodClass) [protected]
Change the current mood field from a Class object.
See Also
currentMood
Definition at line 116 of file AI.java.
References gameplay.ai.AI.currentMood.
Referenced by gameplay.ai.AI.newBetrayal(), and gameplay.ai.AI.newSlavery().
                                                     {
        try {
            Philophobia.getVerbose().information("AI switching from " +
      currentMood.getClass().getName() + " mood to " + moodClass.getName() + " mood", "
      gameplay/ai/AI.java", "AI.changeMood(Class)");
            currentMood = moodClass.newInstance();
        } catch(SecurityException e) {
            Philophobia.getVerbose().serious("Security exception when switching from " +
      currentMood.getClass().getName() + " mood to " + moodClass.getName() + " mood: " + e.getMessage(
      ), "gameplay/ai/AI.java", "AI.changeMood(Class)");
        } catch(InstantiationException e) {
            Philophobia.getVerbose().serious("Instantiation exception when switching from " +
      currentMood.getClass().getName() + " mood to " + moodClass.getName() + " mood: " + e.getMessage(
      ), "gameplay/ai/AI.java", "AI.changeMood(Class)");
        } catch(IllegalAccessException e) {
            Philophobia.getVerbose().serious("Illegal access exception when switching from " +
      currentMood.getClass().getName() + " mood to " + moodClass.getName() + " mood: " + e.getMessage(
      ), "gameplay/ai/AI.java", "AI.changeMood(Class)");
        }
    }
void gameplay.ai.AI.newBetrayal ()
Method called when the player make a new betrayal (does not do what the AI asked)
Definition at line 91 of file AI.java.
References gameplay.ai.AI.betrayalCount, gameplay.ai.AI.changeMood(), gameplay.ai.AI.currentMood, gameplay.ai.mood.Mood.getNextMood(), and gameplay.ai.mood.Mood.incrementBetrayalCount().
                              {
        Philophobia.getVerbose().calls("New betrayal action detected", "gameplay/ai/AI.java", "
      AI.newBetrayal()");
        betrayalCount++;
        if(currentMood.incrementBetrayalCount() >=
      currentMood.getBetrayalThreshold()) {
            changeMood(currentMood.getNextMood());
        }
    }
void gameplay.ai.AI.newSlavery ()
Method called when the player do what the AI asked.
Definition at line 103 of file AI.java.
References gameplay.ai.AI.changeMood(), gameplay.ai.AI.currentMood, gameplay.ai.mood.Mood.getPreviousMood(), gameplay.ai.mood.Mood.incrementSlaveryCount(), and gameplay.ai.AI.slaveryCount.
                             {
        Philophobia.getVerbose().calls("New slavery action detected", "gameplay/ai/AI.java", "
      AI.newSlavery()");
        slaveryCount++;
        if(currentMood.incrementSlaveryCount() >=
      currentMood.getSlaveryThreshold()) {
            changeMood(currentMood.getPreviousMood());
        }
    }
void gameplay.ai.AI.setCurrentWorld (World world)
Setter for the current world field.
See Also
currentWorld
Definition at line 78 of file AI.java.
References gameplay.ai.AI.currentWorld.
                                             {
        currentWorld = world;
    }
Member Data Documentation
int gameplay.ai.AI.betrayalCount [protected]
Number of betrayals done by the player.
Definition at line 52 of file AI.java.
Referenced by gameplay.ai.AI.AI(), and gameplay.ai.AI.newBetrayal().
Mood gameplay.ai.AI.currentMood [protected]
Mood in which the AI is currently in.
Definition at line 42 of file AI.java.
Referenced by gameplay.ai.AI.AI(), gameplay.ai.AI.changeMood(), gameplay.ai.AI.newBetrayal(), and gameplay.ai.AI.newSlavery().
World gameplay.ai.AI.currentWorld [protected]
World where the player is currently in.
Definition at line 37 of file AI.java.
Referenced by gameplay.ai.AI.AI(), and gameplay.ai.AI.setCurrentWorld().
Phrasing gameplay.ai.AI.phrasingSystem [protected]
AI talk system.
Definition at line 47 of file AI.java.
Referenced by gameplay.ai.AI.AI().
int gameplay.ai.AI.slaveryCount [protected]
Number of asked actions by the AI done by the player.
Definition at line 58 of file AI.java.
Referenced by gameplay.ai.AI.AI(), and gameplay.ai.AI.newSlavery().
The documentation for this class was generated from the following file:
gameplay/ai/AI.java